### ISSUE TITLE
Post permalink is missing /homepage/

### ISSUE THREAD

**Issue by ashutoshmjain** [JiaKunUp/jalpc_jekyll_theme#46]
Hi @JiaKunUp 

Hope you are doing well ..
I just created  a new test post. The url for the post is  automatically assigned as  'https://ashutoshmjain.github.io/foss/2017/01/17/testpost.html'

As you will notice , its missing  '/homepage/' .. so I am getting a 404 error .  (foss is one of my categories)

Wondering if there is an easy way to fix it  

Thanks in advance for all the help

**Comment by ashutoshmjain** [comment]
btw - I tried changing permalink in foss.html from '/foss/' to '/homepage/foss/'  .. If i do that than the foss page itself ends into a 404 error ...

**Comment by JiaKunUp** [comment]
Hi @ashutoshmjain , thanks again for continuous improving this theme!

When I designed this website, I didn't take suburl as homepage into my consideration.So I haven't noticed this bug yet, but thanks anyway for finding this bug!

I see you have edited a lot of in your reposotory, I think the easiest way of fix this bug is:
at `blog/blog.html` line 26, change `<a href="{{ post.url }}" class="vote-title">` to `<a href="{{ post.url | prepend: site.baseurl }}" class="vote-title">`. 
In addition, another blog url you need to edit is file `_includes/category.html` line 21, change `<a href="{{ post.url }}" class="btn-link">` to `<a href="{{ post.url | prepend: site.baseurl }}" class="btn-link">`.
If you find other urls can't work, this is mainly because the url doesn't have prepend url, you can add it yourself.

I have a new push to fix this bug. Baseurl is `''`, url is `http://www.jack003.com` now, if you are intrested on this new commit, you can review my code. Thanks!

**Comment by ashutoshmjain** [comment]
Sure ..thanks 
I will check it out and close the issue

**Comment by ashutoshmjain** [comment]
It worked  .. thanks

**Comment by ashutoshmjain** [comment]
Btw  - I just made changes to the code you suggested above :1st_place_medal: 
 I am not well aware of how I could pull a specific commit. May be I will learn later if things fell apart

**Comment by JiaKunUp** [comment]
@ashutoshmjain  If you have some links can't work, you can inspect this dom element and check if this url is you want, in the above error: your post url should be like `http://ashutoshmjain.github.io/homepage/bernie/2017/01/17/test-post-02.html` but error post url is `http://ashutoshmjain.github.io/bernie/2017/01/17/test-post-02.html`,  **homepage** is missing, so add `{{ site.baseurl }}` before post url can work.

Thanks.
