### ISSUE TITLE
Question - Publish only Blog to a custom url

### ISSUE THREAD

**Issue by ashutoshmjain** [JiaKunUp/jalpc_jekyll_theme#47]
Hi Jack @JiaKunUp 

I have a question . No hurry for answer .. and I am not expecting any work on this  .. its just a curious question in my mind ..

I have a custom domain (shutri.com) where I publish my blogger posts. I want to publish this blog there . Is there a way that I could publish **https://ashutoshmjain.github.io/homepage/blog to http://shutri.com** ... 

 I don't want to publish the landing page (About me , skills etc.) to my custom domain. Visitor can click on "AmJ" and get transferred to my homepage here on github if they want to know more about me .. 

Thanks 

Ashutosh

**Comment by JiaKunUp** [comment]
Hi @ashutoshmjain ,

I have seen your custom website, it's published at google, I think what you want to realize is to make <https://ashutoshmjain.github.io/homepage/blog> as your index page of website (<http://shutri.com>), and let current index page (landing page) be your profile page, maybe the url is <http://shutri.com/profile/>.

If so, the following way will work:

1. Edit **index.html**'s filename to **profile.html** and change `permalink` to `/profile/` in this file.
2. Move **blog/blog.html** to **index.html** and change `permalink` to `/` in this file.
3. Edit **_includes/header.html** line 24, change it to `<a class="navbar-brand" href="{{ "/profile/" | prepend: site.baseurl }}">{{ site.title }}</a>`, so you can click "AmJ" to transfer to your profile page.
4. Since blog page's url has been changed, profile page's blog link should be changed to `href="{{ "/" | prepend: site.baseurl }}"` from `href="{{ "/blog/" | prepend: site.baseurl }}"` in file **_includes/sections/blog.html**.

I think this will meet your needs. Thanks!

**Comment by ashutoshmjain** [comment]
Thanks a ton  .. This is my weekend project . I will test it out on my local machine first .

**Comment by JiaKunUp** [comment]
OK 👍

**Comment by ashutoshmjain** [comment]
@JiaKunUp 

I figured out an easier workaround  .. 

I just forwarded my other  subdomain (http://ashutosh.86reckers.com/)   to ashutoshmjain.github.io/homepage/blog  for testing ..  It worked. I will now invest time to migrate all my write-ups from blogger , Medium , Wordpress and Linkedin to JalPC.  And once I have good enough content , I will forward Shutri.com to /homepage/blog . I guess , it will take me a while as I want to go thru 10 years worth of writing one by one and check if it make sense in migrate .. And thats the fun part :-)

The approach of forwarding domains (or subdomains) to either '/homepage' or '/homepage/blog' allows me flexibility as to what I want to the landing page to be ... .. eg I am forwarding to /homepage at http://ashutosh.thinkingInSAP.com/

Also , while forwarding the subdomain, I noticed that GoDaddy allows me to mask the url. Which means, the visitor never jumps to my repository url .. I still need to check if it will impact my Google Analytics but thats not a big issue for me as I hardly care for click numbers :-) 

The other advantage of this approach is my website continues to live on GH pages , this allows me continuously improving the code thru issue management and allowing experts like yourself to see what is in my repo .. no need to migrate the code to other host 

Thanks a ton for giving me pointers 

Cheers

**Comment by JiaKunUp** [comment]
@ashutoshmjain 

Awesome!👍 

Just now I used this function at GoDaddy and it looks perfect, with this function you can redirect any  subdomain to gh-pages. I think it's meaningful to merge blogs to GitHub repository, and I wonder if there is a way to export blogs to markdown format files from other websites, if so merging will be easier.

And then I tried share buttons, it will use original website URL as link: when I visit http://**test**.jack003.com, it redirects to http://**www**.jack003.com, but I share article at this website, it shows http://**www**.jack003.com/xxxx. In your website at <http://ashutosh.thinkinginsap.com/> your blog URL is <https://ashutoshmjain.github.io/homepage/blog> and this is still original URL, I think this will be good :)

About Google Analytics, I think GA can figure out redirect URL and use 301 redirect is better than 302, here is an article about 301 and 302 redirect affect in Google Analytics <https://seo-hacker.com/301-302-redirect-affect-seo/>.

Finally, this is a flexible method to accomplish your question.

Thanks and best regards
